<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-16">
<meta name="description" content="A STRING GCN recovers known clinical-stage idiopathic pulmonary fibrosis (IPF) targets at AUPRC 0.322, versus 0.305 for XGBoost and 0.098 for a GCN without edges.">

<title>Drug target identification for idiopathic pulmonary fibrosis (IPF) via geometric deep learning on a knowledge graph – Andres Lanzos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../jpg/photo.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-703069f40e948ba70f3f3e6eba71fad1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-fc15bee6fe409d5dc7e34485bd7b8a48.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;0,8..60,700;1,8..60,400;1,8..60,500&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Drug target identification for idiopathic pulmonary fibrosis (IPF) via geometric deep learning on a knowledge graph – Andres Lanzos">
<meta property="og:description" content="A STRING GCN recovers known clinical-stage idiopathic pulmonary fibrosis (IPF) targets at AUPRC 0.322, versus 0.305 for XGBoost and 0.098 for a GCN without edges.">
<meta property="og:image" content="https://alanzos.github.io/portfolio/articles/2026-08-16-ipf-target-ranker/image.png">
<meta property="og:site_name" content="Andres Lanzos">
<meta property="og:image:height" content="1536">
<meta property="og:image:width" content="1024">
<meta property="og:image:alt" content="Infographic: STRING-GCN recovers known IPF targets at AUPRC 0.322 versus 0.305 for XGBoost and 0.098 for a GCN without edges">
<meta name="twitter:title" content="Drug target identification for idiopathic pulmonary fibrosis (IPF) via geometric deep learning on a knowledge graph – Andres Lanzos">
<meta name="twitter:description" content="A STRING GCN recovers known clinical-stage idiopathic pulmonary fibrosis (IPF) targets at AUPRC 0.322, versus 0.305 for XGBoost and 0.098 for a GCN without edges.">
<meta name="twitter:image" content="https://alanzos.github.io/portfolio/articles/2026-08-16-ipf-target-ranker/image.png">
<meta name="twitter:image-height" content="1536">
<meta name="twitter:image-width" content="1024">
<meta name="twitter:image:alt" content="Infographic: STRING-GCN recovers known IPF targets at AUPRC 0.322 versus 0.305 for XGBoost and 0.098 for a GCN without edges">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Andres Lanzos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../articles/index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../articles/index.xml"> <i class="bi bi-rss" role="img" aria-label="Articles RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:andreslanzos@gmail.com"> <i class="bi bi-envelope" role="img" aria-label="Email Andres Lanzos">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/andreslanzos/"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn profile">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/alanzos"> <i class="bi bi-github" role="img" aria-label="GitHub profile">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#goals" id="toc-goals" class="nav-link active" data-scroll-target="#goals"><span class="header-section-number">1</span> Goals</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#models" id="toc-models" class="nav-link" data-scroll-target="#models"><span class="header-section-number">3.1</span> Models</a></li>
  <li><a href="#training-validation-and-testing" id="toc-training-validation-and-testing" class="nav-link" data-scroll-target="#training-validation-and-testing"><span class="header-section-number">3.2</span> Training, validation, and testing</a></li>
  <li><a href="#benchmark-metrics" id="toc-benchmark-metrics" class="nav-link" data-scroll-target="#benchmark-metrics"><span class="header-section-number">3.3</span> Benchmark metrics</a></li>
  <li><a href="#feature-importance" id="toc-feature-importance" class="nav-link" data-scroll-target="#feature-importance"><span class="header-section-number">3.4</span> Feature importance</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance"><span class="header-section-number">4.1</span> Model performance</a></li>
  <li><a href="#feature-importance-1" id="toc-feature-importance-1" class="nav-link" data-scroll-target="#feature-importance-1"><span class="header-section-number">4.2</span> Feature importance</a></li>
  <li><a href="#target-ranking" id="toc-target-ranking" class="nav-link" data-scroll-target="#target-ranking"><span class="header-section-number">4.3</span> Target ranking</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5</span> Conclusions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Drug target identification for idiopathic pulmonary fibrosis (IPF) via geometric deep learning on a knowledge graph</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine learning</div>
    <div class="quarto-category">Target identification</div>
    <div class="quarto-category">Knowledge Graph</div>
    <div class="quarto-category">Neural Network</div>
  </div>
  </div>

<div>
  <div class="description">
    A STRING GCN recovers known clinical-stage idiopathic pulmonary fibrosis (IPF) targets at AUPRC 0.322, versus 0.305 for XGBoost and 0.098 for a GCN without edges.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026-08-16</p>
            <p class="reading-time">14 min</p>
          </div>
  </div>
  
    
  </div>
  


</header>


<section id="goals" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="goals"><span class="header-section-number">1</span> Goals</h2>
<p>Back at my data-scientist role at Idorsia, one of our main mandates was to identify new drug targets for focus diseases. We used a mix of methods: simple differential expression between disease and healthy samples, gradient boosting, and more advanced geometric models and autoencoders.</p>
<p>I wanted to take those learnings to idiopathic pulmonary fibrosis (IPF). It is relatively rare, yet a high-priority disease: progressive lung scarring <span class="citation" data-cites="raghu2011ipf">[<a href="#ref-raghu2011ipf" role="doc-biblioref">1</a>]</span>, historically a median survival of about 3 to 5 years after diagnosis <span class="citation" data-cites="ley2011course">[<a href="#ref-ley2011course" role="doc-biblioref">2</a>]</span>, a severe quality-of-life burden, high cost per patient <span class="citation" data-cites="yang2026ipfcost">[<a href="#ref-yang2026ipfcost" role="doc-biblioref">3</a>]</span>, and only a handful of antifibrotics that slow decline <span class="citation" data-cites="king2014pirfenidone richeldi2014nintedanib">[<a href="#ref-king2014pirfenidone" role="doc-biblioref">4</a>,<a href="#ref-richeldi2014nintedanib" role="doc-biblioref">5</a>]</span>. Lung transplantation is the one potentially curative option. The medical need is obvious; the biology is hard (epithelial injury, fibroblasts, TGF-β, extracellular matrix) <span class="citation" data-cites="fernandez2012tgfb">[<a href="#ref-fernandez2012tgfb" role="doc-biblioref">6</a>]</span>. IPF was a natural disease in which to ask whether a protein knowledge graph, used as structure in a GCN <span class="citation" data-cites="kipf2017gcn">[<a href="#ref-kipf2017gcn" role="doc-biblioref">7</a>]</span>, recovers more information than simpler models on the same public features. In other words: does the extra complexity pay off?</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image.png" class="img-fluid figure-img" alt="Infographic summarizing the IPF ranker: STRING-GCN AUPRC 0.322, XGBoost 0.305, GCN without edges 0.098, Open Targets 0.329 as the positive control."></p>
<figcaption>STRING edges earn their keep for IPF target ranking</figcaption>
</figure>
</div>
</section>
<section id="data" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data"><span class="header-section-number">2</span> Data</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Piece</th>
<th>Freeze</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Disease</td>
<td>IPF (<code>EFO_0000768</code>)</td>
</tr>
<tr class="even">
<td>Universe</td>
<td>4,283 Open Targets associated genes <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span></td>
</tr>
<tr class="odd">
<td>Labels</td>
<td>139 genes with a clinical-stage mechanism of action (phase ≥ 1)</td>
</tr>
<tr class="even">
<td>Chance AUPRC</td>
<td>0.032 (prevalence)</td>
</tr>
<tr class="odd">
<td>Graph</td>
<td>STRING v12, combined score ≥ 700 <span class="citation" data-cites="szklarczyk2023string">[<a href="#ref-szklarczyk2023string" role="doc-biblioref">9</a>]</span></td>
</tr>
</tbody>
</table>
<p>I used 18 public features, one row per gene. Each feature is numeric and rank-scaled toward [0, 1]; 0 means no evidence in that feature.</p>
<p><strong>Genetics.</strong> Open Targets genetic association for IPF <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span>, plus a sparse GWAS Catalog flag for IPF and interstitial-lung-disease genes <span class="citation" data-cites="sollis2023gwas">[<a href="#ref-sollis2023gwas" role="doc-biblioref">10</a>]</span>.</p>
<p><strong>Expression and tissue.</strong> A GEO meta-analysis of IPF versus control lung series <span class="citation" data-cites="barrett2013geo">[<a href="#ref-barrett2013geo" role="doc-biblioref">11</a>]</span>, the Open Targets RNA-expression association <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span>, lung specificity from GTEx <span class="citation" data-cites="gtex2020">[<a href="#ref-gtex2020" role="doc-biblioref">12</a>]</span> and the Human Protein Atlas <span class="citation" data-cites="uhlen2015hpa">[<a href="#ref-uhlen2015hpa" role="doc-biblioref">13</a>]</span>, and a combined feature that takes the max of those lung-expression views.</p>
<p><strong>Pathways and regulation.</strong> Membership in Reactome pathways enriched among differential-expression seeds <span class="citation" data-cites="gillespie2022reactome">[<a href="#ref-gillespie2022reactome" role="doc-biblioref">14</a>]</span>; a transcription-factor feature whose targets match the GEO signature, from CollecTRI <span class="citation" data-cites="mullerdott2023collectri">[<a href="#ref-mullerdott2023collectri" role="doc-biblioref">15</a>]</span>; Open Targets animal-model evidence <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span>.</p>
<p><strong>STRING neighborhood.</strong> Tabular geometry on the same protein network the GCN later uses <span class="citation" data-cites="szklarczyk2023string">[<a href="#ref-szklarczyk2023string" role="doc-biblioref">9</a>]</span>: how many neighbors are IPF-changed genes, whether the gene sits in a community of those genes, a network walk from them, centrality in IPF gene modules, and the same module idea seeded by genetics. The GCN still mixes those features along edges.</p>
<p><strong>Perturbation.</strong> LINCS L1000 knockdown and overexpression connectivity versus the IPF DE signature <span class="citation" data-cites="subramanian2017lincs">[<a href="#ref-subramanian2017lincs" role="doc-biblioref">16</a>]</span>, and DepMap CRISPR essentiality averaged over lung cancer lines <span class="citation" data-cites="tsherniak2017depmap">[<a href="#ref-tsherniak2017depmap" role="doc-biblioref">17</a>]</span>. That last feature is a lung prior, not an IPF prior.</p>
<p>The model input is those 18 features. The labels are a known-drug proxy: 139 genes with a clinical-stage mechanism of action (phase ≥ 1). Genes without that label stay unlabeled (positive-unlabeled ranking). I kept Open Targets clinical association out of the features; it defines the labels.</p>
<p>The implementation for this freeze is private.</p>
</section>
<section id="methods" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="methods"><span class="header-section-number">3</span> Methods</h2>
<section id="models" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="models"><span class="header-section-number">3.1</span> Models</h3>
<p>I trained every model on the same 18 features. Graph models also saw STRING edges. That isolates architecture from feature engineering.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>What it is</th>
<th>Strength</th>
<th>Limit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>XGBoost</strong></td>
<td>Gradient-boosted trees on the 18 features. Inductive: a held-out gene is predicted from its row alone.</td>
<td>Strong default on mixed, sparse tabular features; early stopping is straightforward.</td>
<td>No message passing. STRING geometry only enters through neighborhood features I already computed.</td>
</tr>
<tr class="even">
<td><strong>Tabular neural net</strong></td>
<td>Two-layer net (64 then 32), dropout 0.3.</td>
<td>Nonlinear tabular control without trees.</td>
<td>Few labeled genes; overfits more easily than trees on this matrix.</td>
</tr>
<tr class="odd">
<td><strong>STRING-GCN</strong></td>
<td>Two GCN layers, hidden 32, using STRING confidence as the edge weight. Each gene takes a degree-normalized average of its neighbors <span class="citation" data-cites="kipf2017gcn">[<a href="#ref-kipf2017gcn" role="doc-biblioref">7</a>]</span>.</td>
<td>Cheap mixer; matches homophilous PPI; uses the combined STRING score.</td>
<td>Neighbors are mixed uniformly (up to degree and edge weight). Training is transductive.</td>
</tr>
<tr class="even">
<td><strong>STRING-GAT</strong></td>
<td>Two GAT layers, 16 hidden units × 4 heads <span class="citation" data-cites="velickovic2018gat">[<a href="#ref-velickovic2018gat" role="doc-biblioref">18</a>]</span>.</td>
<td>Can down-weight unhelpful neighbors.</td>
<td>More parameters; this freeze drops edge weights; ~111 labeled genes per train fold and ~82k edges. Attention is extra capacity that may not pay.</td>
</tr>
<tr class="odd">
<td><strong>GCN without edges</strong></td>
<td>Same GCN, empty edge set (self-loops only).</td>
<td>The control that shows whether edges add anything.</td>
<td>Not a production ranker.</td>
</tr>
<tr class="even">
<td><strong>GCN on degree only</strong></td>
<td>STRING edges, features reduced to degree.</td>
<td>Hub check: tests whether ranking is high-degree proteins first.</td>
<td>Throws away the 18 features.</td>
</tr>
<tr class="odd">
<td><strong>Shuffled labels</strong></td>
<td>Same XGBoost, labels permuted.</td>
<td>Sanity check that AUPRC is not a metric bug.</td>
<td>Not a ranker.</td>
</tr>
<tr class="even">
<td><strong>Open Targets</strong></td>
<td>Frozen Open Targets overall association. Not trained. The <strong>positive control</strong>.</td>
<td>Combines every Open Targets evidence type, including the clinical evidence that defines the labels <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span>. That is the strongest public Open Targets ranking I can put on the same genes.</td>
<td>The clinical evidence that defines the labels sits inside this score.</td>
</tr>
</tbody>
</table>
<p>I compared STRING-GCN with GCN without edges and with XGBoost. GAT is the attention alternative on the same graph.</p>
</section>
<section id="training-validation-and-testing" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="training-validation-and-testing"><span class="header-section-number">3.2</span> Training, validation, and testing</h3>
<p>The unit is a gene, not a sample. I split with <strong>repeated stratified 5-fold CV</strong> (<code>RepeatedStratifiedKFold</code>, 5 splits × 5 repeats, seed 42).</p>
<p><strong>Stratified.</strong> There are only 139 labeled genes in 4,283 (about 3%). A random fold can easily get too few labeled genes for AUPRC to mean anything. Stratifying on the labels keeps that prevalence in every test fold (about 28 labeled genes among ~857 genes).</p>
<p><strong>5-fold.</strong> In one pass, the universe is partitioned into five test sets. Each gene is held out as <strong>test once</strong>. The other four fifths are the outer pool for that fold, then split 80/20 into train and early-stopping validation, so a gene is not in the training loss on all four of those folds.</p>
<p><strong>Repeated.</strong> AUPRC on ~28 labeled genes is noisy. I shuffled and repeated the 5-fold partition five times, still with seed 42. That gives <strong>25 test folds</strong>. The numbers I report are mean ± sd over those 25 evaluations, not a single lucky split. Across repeats a gene is held out more than once; the illustration ranking later averages those held-out predictions.</p>
<p><strong>Train / validation / test inside each fold.</strong> The outer test genes (~857) are metrics only. The remaining genes split 80/20 into train (~2,740) and validation (~686). Validation is early stopping only: XGBoost watches AUPRC for 40 rounds; GCN and GAT watch full-graph validation AUPRC with patience 15; the tabular neural net uses patience 12. Test genes never enter the loss, the stopper, or the scaler fit. I froze hyperparameters before this confirmation run. The inner split is not a nested search.</p>
<p>XGBoost and the tabular neural net are inductive: a held-out gene is predicted from its features alone. The GNN is transductive: one forward pass on the full 4,283-gene graph each epoch, with binary cross-entropy only on train genes. I masked test labels. Test features still flow on STRING edges, so a test gene can be predicted from its neighbors. That is why I needed GCN without edges: it is the comparison that answers whether the graph helped.</p>
<p>Class imbalance is handled with a class weight from the training counts. Unlabeled genes stay unlabeled; I did not downsample them away.</p>
</section>
<section id="benchmark-metrics" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="benchmark-metrics"><span class="header-section-number">3.3</span> Benchmark metrics</h3>
<p>I used <strong>AUPRC</strong> on held-out genes as the comparison, mean ± sd over the 25 test folds. That is the usual cross-validation summary: one AUPRC per held-out slice, then the mean. Chance AUPRC equals prevalence, about 0.032. With 3% labeled genes, AUROC can look fine while the top of the list is junk <span class="citation" data-cites="saito2015auprc">[<a href="#ref-saito2015auprc" role="doc-biblioref">19</a>]</span>. Accuracy is worse: a model that ranks nobody still looks 97% correct.</p>
<p>The comparisons I care about are STRING-GCN versus GCN without edges (whether edges helped), versus XGBoost (whether geometry beat trees on the same features), versus shuffled labels (whether anything sat above chance), and versus Open Targets (the positive control).</p>
<p>Open Targets overall already mixes genetics, expression, animal models, text, and known-drug / clinical evidence into one association <span class="citation" data-cites="ochoa2023opentargets">[<a href="#ref-ochoa2023opentargets" role="doc-biblioref">8</a>]</span>. The clinical piece is the same evidence that defines the labels, which I kept out of the 18 features. That is why it is the positive control: the strongest public Open Targets ranking on these genes, clinical evidence included.</p>
<p>For each trained model I paired the 25 fold AUPRCs with the Open Targets AUPRC on the same test genes and ran a two-sided Wilcoxon signed-rank test on those differences <span class="citation" data-cites="wilcoxon1945">[<a href="#ref-wilcoxon1945" role="doc-biblioref">20</a>]</span>. Seven models, so I Holm-adjusted the p-values <span class="citation" data-cites="holm1979">[<a href="#ref-holm1979" role="doc-biblioref">21</a>]</span>. The AUPRC plot writes those tests after each mean ± sd: n.s. if p ≥ 0.05, one star if p &lt; 0.05, two stars if p &lt; 0.01, three stars if p &lt; 0.001.</p>
</section>
<section id="feature-importance" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="feature-importance"><span class="header-section-number">3.4</span> Feature importance</h3>
<p>I ranked the 18 features by how much the trained STRING-GCN depends on each one. On the same 25 test folds as the confirmation run, I trained STRING-GCN, recorded held-out AUPRC, then shuffled one feature on every gene and recorded held-out AUPRC again. The drop is baseline minus shuffled. I average those drops over the 25 folds. The trained weights stay fixed; only that feature is shuffled. Because training is transductive, the shuffle hits every gene, so neighbors lose that feature too.</p>
</section>
</section>
<section id="results" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="results"><span class="header-section-number">4</span> Results</h2>
<section id="model-performance" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="model-performance"><span class="header-section-number">4.1</span> Model performance</h3>
<p>Each of the 25 test folds has its own AUPRC on the held-out genes. The comparison is the mean ± sd of those 25 numbers. Stars after each number are Holm-adjusted Wilcoxon tests against Open Targets.</p>
<div class="light-content">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="auprc_cv.png" class="img-fluid figure-img" alt="Horizontal pill bars of mean AUPRC across 25 test folds. A white marker sits at the mean; a rounded whisker is plus or minus one standard deviation. Holm stars sit after each mean plus or minus sd: STRING-GCN and XGBoost are n.s., STRING-GAT is one star, the remaining four are three stars. A dashed line marks chance at 0.032. A legend defines n.s., one star, two stars, and three stars."></p>
<figcaption>AUPRC across 25 test folds, with Holm-adjusted Wilcoxon vs Open Targets</figcaption>
</figure>
</div>
</div>
<div class="dark-content">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="auprc_cv-dark.png" class="img-fluid figure-img" alt="Horizontal pill bars of mean AUPRC across 25 test folds. A light marker sits at the mean; a rounded whisker is plus or minus one standard deviation. Holm stars sit after each mean plus or minus sd: STRING-GCN and XGBoost are n.s., STRING-GAT is one star, the remaining four are three stars. A dashed line marks chance at 0.032. A legend defines n.s., one star, two stars, and three stars."></p>
<figcaption>AUPRC across 25 test folds, with Holm-adjusted Wilcoxon vs Open Targets</figcaption>
</figure>
</div>
</div>
<p>STRING-GCN was the trained winner. It beat GCN without edges in <strong>25/25</strong> folds (mean AUPRC lift about 0.22). The protein knowledge graph added information: the same architecture, without STRING edges, fell near 0.10. GCN on degree only stayed near 0.09, so the lift is neighborhood mixing of the features, not a ranking of hubs.</p>
<p>It tied XGBoost (GCN ahead on 16/25 folds, overlapping SDs). Trees already see precomputed STRING neighborhood features; the GCN still gained by mixing those features along the actual edges. The tabular neural net lagged both (0.165): a small net overfits this 3% labeled matrix more than depth-4 trees.</p>
<p>GAT lost to GCN on 21/25 folds. The remaining information is homophilous STRING mixing: a gene looks like its neighbors. A degree-normalized average matches that bias. With ~111 labeled genes per train fold and 82k edges, GCN was the mixer that fit. GAT still beat GCN without edges, so attention was running; it was the worse inductive bias here.</p>
<p>STRING-GCN matched the positive control on AUPRC (n.s., Δ -0.008). XGBoost did too (n.s., Δ -0.025). STRING-GAT sat below Open Targets (0.274, Holm p &lt; 0.05). The remaining controls sat well below (Holm p &lt; 0.001).</p>
<p>Shuffled labels is the sanity check: same XGBoost, labels permuted. AUPRC fell to 0.038, which is chance (0.032). The metric is not inventing a ranking from the 3% prevalence.</p>
<p>What STRING-GCN recovered at 0.322 is therefore a real ranking of known clinical-stage mechanisms, from the 18 features that omit the clinical evidence. Open Targets overall is close (0.329) because that public score includes that evidence.</p>
</section>
<section id="feature-importance-1" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="feature-importance-1"><span class="header-section-number">4.2</span> Feature importance</h3>
<p>I ranked the 18 features by mean AUPRC drop in the winning STRING-GCN: how much held-out AUPRC falls after shuffling that feature on every gene (neighbors lose it too).</p>
<div class="light-content">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gcn_feature_importance.png" class="img-fluid figure-img" alt="Horizontal pill bars of mean AUPRC drop after shuffling each of the 18 features in the trained STRING-GCN. Genetics-linked gene modules lead at 0.052, then matching transcription factors at 0.050 and lung-cell essentiality at 0.045."></p>
<figcaption>STRING-GCN feature importance as mean AUPRC drop</figcaption>
</figure>
</div>
</div>
<div class="dark-content">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gcn_feature_importance-dark.png" class="img-fluid figure-img" alt="Horizontal pill bars of mean AUPRC drop after shuffling each of the 18 features in the trained STRING-GCN. Genetics-linked gene modules lead at 0.052, then matching transcription factors at 0.050 and lung-cell essentiality at 0.045."></p>
<figcaption>STRING-GCN feature importance as mean AUPRC drop</figcaption>
</figure>
</div>
</div>
<p>Genetics-linked gene modules, matching transcription factors, and lung-cell essentiality are the three features the trained GCN leans on (drops 0.052, 0.050, 0.045). STRING neighborhood features come next: IPF-changed genes as neighbors, community, the network walk, and module centrality. GEO lung expression, GWAS flags, animal models, and Open Targets RNA sit at the bottom (drops near 0).</p>
</section>
<section id="target-ranking" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="target-ranking"><span class="header-section-number">4.3</span> Target ranking</h3>
<p>I looked at out-of-fold STRING-GCN predictions for illustration (each gene’s prediction is the mean of the folds that held it out). <strong>Known</strong> means the gene is one of the 139 clinical-stage mechanisms I used as labels (phase ≥ 1). <strong>Novel</strong> means it is not: a hypothesis on this freeze, not a recovered training example.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Gene</th>
<th>Known or novel</th>
<th style="text-align: right;">STRING-GCN</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TGFB1</td>
<td>Known</td>
<td style="text-align: right;">0.61</td>
<td>Canonical fibrosis biology <span class="citation" data-cites="fernandez2012tgfb">[<a href="#ref-fernandez2012tgfb" role="doc-biblioref">6</a>]</span></td>
</tr>
<tr class="even">
<td>TNF</td>
<td>Known</td>
<td style="text-align: right;">0.71</td>
<td>Neighborhood lifts a known mechanism</td>
</tr>
<tr class="odd">
<td>PDGFRB</td>
<td>Known</td>
<td style="text-align: right;">0.58</td>
<td>Nintedanib-family target <span class="citation" data-cites="richeldi2014nintedanib">[<a href="#ref-richeldi2014nintedanib" role="doc-biblioref">5</a>]</span></td>
</tr>
<tr class="even">
<td>MUC5B</td>
<td>Novel</td>
<td style="text-align: right;">0.33</td>
<td>Famous IPF risk gene; stays mid-rank <span class="citation" data-cites="seibold2011muc5b">[<a href="#ref-seibold2011muc5b" role="doc-biblioref">22</a>]</span></td>
</tr>
<tr class="odd">
<td>COX7B</td>
<td>Novel</td>
<td style="text-align: right;">0.77</td>
<td>Top novel hit: respiratory-chain hub</td>
</tr>
</tbody>
</table>
<p>The model recovered known clinical mechanisms in the TGF-β, TNF, and PDGFR families without putting clinical association into the features. TNF was the clearest neighborhood lift: XGBoost predicted 0.47; the GCN predicted 0.71.</p>
<p>MUC5B is the genetic signature of IPF risk and is Novel in this table: it is not a clinical-stage mechanism under the definition of the labels. Mid-rank is the honest outcome: a risk gene is not the same decision as a drug mechanism.</p>
<p>Those high novel ranks (COX7B, other respiratory-chain subunits, HRAS, MAPK1) are the genes I would prioritize for a chemist or a biologist. They are shaped by the same STRING geometry that recovered the known targets.</p>
</section>
</section>
<section id="conclusions" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">5</span> Conclusions</h2>
<p>I started this freeze with a question from target identification: on public IPF data, does a protein knowledge graph earn its keep, or do trees on the same 18 features already do the job? On the confirmation metric, mean AUPRC across 25 test folds, the graph earned it. STRING-GCN recovered known clinical-stage mechanisms at <strong>0.322</strong>. XGBoost on the same features reached <strong>0.305</strong>. The same GCN with the STRING edges deleted fell to <strong>0.098</strong>, in every fold. The lift is neighborhood mixing of the features, not a more fashionable architecture and not a ranking of hubs.</p>
<p>That trained ranking sat next to Open Targets overall at 0.329. Open Targets is the positive control: it already combines every evidence type in that database, including the clinical evidence that defines the labels, which I kept out of the 18 features. I am not offering a better Open Targets. I am offering a GCN that, from genetics, tissue, pathways, perturbation, and STRING, recovers a neighborhood-shaped trace of the same mechanisms, close enough that a Wilcoxon test cannot tell the two lists apart.</p>
<p>What the GCN used matches that picture. It leans on genetics-linked modules, transcription factors whose targets match the IPF signature, and lung-cell essentiality, then on STRING neighborhood. It does not lean on a GEO volcano plot. Known mechanisms in the TGF-β, TNF, and PDGFR families come back without a known-drug column. High novel ranks such as COX7B are the next conversation with a chemist: hypotheses shaped by the same geometry, not recovered labels. MUC5B staying mid-rank is the other honest outcome. A famous risk gene is not a drug mechanism.</p>
<p>This freeze is still a laptop experiment: public features, one disease, a known-drug proxy as the labels, a transductive GNN. DepMap is essentiality in lung cancer lines, not IPF tissue. If I ran the same question inside a company I would train on older evidence and test on clinical-stage genes that only appeared later, use an indication-specific graph, and add chemist labels.</p>
</section>
<section id="references" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="references"><span class="header-section-number">6</span> References</h2>
<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-raghu2011ipf" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Ganesh Raghu, Harold R Collard, Jim J Egan, Fernando J Martinez, Jürgen Behr, Kevin K Brown, Thomas V Colby, Jean-François Cordier, Kevin R Flaherty, Joseph A Lasky, David A Lynch, Jay H Ryu, Jeffrey J Swigris, Athol U Wells, Julio Ancochea, Demosthenes Bouros, Carlos Carvalho, Ulrich Costabel, Masahito Ebina, David M Hansell, Takeshi Johkoh, Dong Soon Kim, Talmadge E King, Yasuhiro Kondoh, Jeffrey Myers, Nestor L Müller, Andrew G Nicholson, Luca Richeldi, Moisés Selman, Rosalind F Dudden, Barbara S Griss, Shandra L Protzko, Holger J Schünemann. An official <span>ATS</span>/<span>ERS</span>/<span>JRS</span>/<span>ALAT</span> statement: Idiopathic pulmonary fibrosis: Evidence-based guidelines for diagnosis and management. American Journal of Respiratory and Critical Care Medicine. 2011;183(6):788–824. doi:<a href="https://doi.org/10.1164/rccm.2009-040GL">10.1164/rccm.2009-040GL</a></div>
</div>
<div id="ref-ley2011course" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Brett Ley, Harold R Collard, Talmadge E King. Clinical course and prediction of survival in idiopathic pulmonary fibrosis. American Journal of Respiratory and Critical Care Medicine. 2011;183(4):431–40. doi:<a href="https://doi.org/10.1164/rccm.201006-0894CI">10.1164/rccm.201006-0894CI</a></div>
</div>
<div id="ref-yang2026ipfcost" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Joseph Yang, Rebecca Fee, Andrea Steffens, Lisa Le, Bonnie H Bui, Bijan J Borah. Real-world health care resource utilization and economic burden among patients with idiopathic pulmonary fibrosis in commercially insured and <span>Medicare</span> <span>Advantage</span> populations in the <span>United</span> <span>States</span>. Journal of Health Economics and Outcomes Research. 2026;13(1):200–9. doi:<a href="https://doi.org/10.36469/001c.161503">10.36469/001c.161503</a></div>
</div>
<div id="ref-king2014pirfenidone" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Talmadge E King, Williamson Z Bradford, Socorro Castro-Bernardini, Elizabeth A Fagan, Ian Glaspole, Marilyn K Glassberg, Eduard Gorina, Peter M Hopkins, David Kardatzke, Lisa Lancaster, David J Lederer, Steven D Nathan, Carlos A Pereira, Steven A Sahn, Robert Sussman, Jeffrey J Swigris, Paul W Noble. A phase 3 trial of pirfenidone in patients with idiopathic pulmonary fibrosis. The New England Journal of Medicine. 2014;370(22):2083–92. doi:<a href="https://doi.org/10.1056/NEJMoa1402582">10.1056/NEJMoa1402582</a></div>
</div>
<div id="ref-richeldi2014nintedanib" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Luca Richeldi, Roland M du Bois, Ganesh Raghu, Arata Azuma, Kevin K Brown, Ulrich Costabel, Vincent Cottin, Kevin R Flaherty, David M Hansell, Yoshikazu Inoue, Dong Soon Kim, Martin Kolb, Andrew G Nicholson, Paul W Noble, Moisés Selman, Hiroyuki Taniguchi, Michèle Brun, Florence Le Maulf, Mannaïg Girard, Susanne Stowasser, Rozsa Schlenker-Herceg, Bernd Disse, Harold R Collard. Efficacy and safety of nintedanib in idiopathic pulmonary fibrosis. The New England Journal of Medicine. 2014;370(22):2071–82. doi:<a href="https://doi.org/10.1056/NEJMoa1402584">10.1056/NEJMoa1402584</a></div>
</div>
<div id="ref-fernandez2012tgfb" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Isis E Fernandez, Oliver Eickelberg. The impact of <span>TGF</span>-β on lung fibrosis: From targeting to biomarkers. Proceedings of the American Thoracic Society. 2012;9(3):111–6. doi:<a href="https://doi.org/10.1513/pats.201203-023AW">10.1513/pats.201203-023AW</a></div>
</div>
<div id="ref-kipf2017gcn" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Thomas N Kipf, Max Welling. Semi-supervised classification with graph convolutional networks. In: International conference on learning representations [Internet]. 2017. Available from: <a href="https://openreview.net/forum?id=SJU4ayYgl">https://openreview.net/forum?id=SJU4ayYgl</a></div>
</div>
<div id="ref-ochoa2023opentargets" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">David Ochoa, Andrew Hercules, Miguel Carmona, Daniel Suveges, Jarrod Baker, Cinzia Malangone, Irene Lopez, Alfredo Miranda, Carlos Cruz-Castillo, Luca Fumis, Manuel Bernal Llinares, Kirill Tsukanov, Helena Cornu, Konstantinos D Tsirigos, Olesya Razuvayevskaya, Annalisa Buniello, Jeremy Schwartzentruber, Mohd Anisul Karim, Bruno Ariano, Ricardo Esteban Martinez Osorio, Javier Ferrer, Xiangyu Ge, Sandra Machlitt-Northen, Asier Gonzalez-Uriarte, Shyamasree Saha, Santosh Tirunagari, Chintan Mehta, Juan María Roldán-Romero, Stuart Horswell, Sarah Young, Maya Ghoussaini, David G Hulcoop, Ian Dunham, Ellen M McDonagh. The next-generation <span>Open</span> <span>Targets</span> <span>Platform</span>: Reimagined, redesigned, rebuilt. Nucleic Acids Research. 2023;51(D1):D1353–9. doi:<a href="https://doi.org/10.1093/nar/gkac1046">10.1093/nar/gkac1046</a></div>
</div>
<div id="ref-szklarczyk2023string" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Damian Szklarczyk, Rebecca Kirsch, Mikaela Koutrouli, Katerina Nastou, Farrokh Mehryary, Radja Hachilif, Annika L Gable, Tao Fang, Nadezhda T Doncheva, Sampo Pyysalo, Peer Bork, Lars J Jensen, Christian von Mering. The <span>STRING</span> database in 2023: Protein–protein association networks and functional enrichment analyses for any sequenced genome of interest. Nucleic Acids Research. 2023;51(D1):D638–46. doi:<a href="https://doi.org/10.1093/nar/gkac1000">10.1093/nar/gkac1000</a></div>
</div>
<div id="ref-sollis2023gwas" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Elliot Sollis, Abayomi Mosaku, Ala Abid, Annalisa Buniello, Maria Cerezo, Laurent Gil, Tudor Groza, Osman Güneş, Peggy Hall, James Hayhurst, Arwa Ibrahim, Yue Ji, Sajo John, Elizabeth Lewis, Jacqueline A L MacArthur, Aoife McMahon, David Osumi-Sutherland, Kalliope Panoutsopoulou, Zoë Pendlington, Santhi Ramachandran, Ray Stefancsik, Jonathan Stewart, Patricia Whetzel, Robert Wilson, Lucia Hindorff, Fiona Cunningham, Samuel A Lambert, Michael Inouye, Helen Parkinson, Laura W Harris. The <span>NHGRI</span>-<span>EBI</span> <span>GWAS</span> catalog: Knowledgebase and deposition resource. Nucleic Acids Research. 2023;51(D1):D977–85. doi:<a href="https://doi.org/10.1093/nar/gkac1010">10.1093/nar/gkac1010</a></div>
</div>
<div id="ref-barrett2013geo" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Tanya Barrett, Stephen E Wilhite, Pierre Ledoux, Carlos Evangelista, Irene F Kim, Maxim Tomashevsky, Kimberly A Marshall, Katherine H Phillippy, Patti M Sherman, Michelle Holko, Andrey Yefanov, Hyeseung Lee, Naigong Zhang, Cynthia L Robertson, Nadezhda Serova, Sean Davis, Alexandra Soboleva. <span>NCBI</span> <span>GEO</span>: Archive for functional genomics data sets—update. Nucleic Acids Research. 2013;41(D1):D991–5. doi:<a href="https://doi.org/10.1093/nar/gks1193">10.1093/nar/gks1193</a></div>
</div>
<div id="ref-gtex2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">GTEx Consortium. The <span>GTEx</span> consortium atlas of genetic regulatory effects across human tissues. Science. 2020;369(6509):1318–30. doi:<a href="https://doi.org/10.1126/science.aaz1776">10.1126/science.aaz1776</a></div>
</div>
<div id="ref-uhlen2015hpa" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Mathias Uhlén, Linn Fagerberg, Björn M Hallström, Cecilia Lindskog, Per Oksvold, Adil Mardinoglu, Åsa Sivertsson, Caroline Kampf, Evelina Sjöstedt, Anna Asplund, IngMarie Olsson, Karolina Edlund, Emma Lundberg, Sanjay Navani, Cristina Al-Khalili Szigyarto, Jacob Odeberg, Dijana Djureinovic, Jenny Ottosson Takanen, Sophia Hober, Tove Alm, Per-Henrik Edqvist, Holger Berling, Hanna Tegel, Jan Mulder, Johan Rockberg, Peter Nilsson, Jochen M Schwenk, Marica Hamsten, Kalle von Feilitzen, Mattias Forsberg, Lukas Persson, Fredric Johansson, Martin Zwahlen, Gunnar von Heijne, Jens Nielsen, Fredrik Pontén. Tissue-based map of the human proteome. Science. 2015;347(6220):1260419. doi:<a href="https://doi.org/10.1126/science.1260419">10.1126/science.1260419</a></div>
</div>
<div id="ref-gillespie2022reactome" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Marc Gillespie, Bijay Jassal, Ralf Stephan, Marija Milacic, Karen Rothfels, Andrea Senff-Ribeiro, Johannes Griss, Cristoffer Sevilla, Lisa Matthews, Chuqiao Gong, Chuan Deng, Thawfeek Varusai, Eliot Ragueneau, Yusra Haider, Bruce May, Veronica Shamovsky, Joel Weiser, Timothy Brunson, Nasim Sanati, Liam Beckman, Xiang Shao, Antonio Fabregat, Konstantinos Sidiropoulos, Julieth Murillo, Guilherme Viteri, Justin Cook, Solomon Shorser, Gary Bader, Emek Demir, Chris Sander, Robin Haw, Guanming Wu, Lincoln Stein, Henning Hermjakob, Peter D’Eustachio. The reactome pathway knowledgebase 2022. Nucleic Acids Research. 2022;50(D1):D687–92. doi:<a href="https://doi.org/10.1093/nar/gkab1028">10.1093/nar/gkab1028</a></div>
</div>
<div id="ref-mullerdott2023collectri" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Sophia Müller-Dott, Eirini Tsirvouli, Miguel Vazquez, Ricardo O Ramirez Flores, Pau Badia-i-Mompel, Robin Fallegger, Dénes Türei, Astrid Lægreid, Julio Saez-Rodriguez. Expanding the coverage of regulons from high-confidence prior knowledge for accurate estimation of transcription factor activities. Nucleic Acids Research. 2023;51(20):10934–49. doi:<a href="https://doi.org/10.1093/nar/gkad841">10.1093/nar/gkad841</a></div>
</div>
<div id="ref-subramanian2017lincs" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Aravind Subramanian, Rajiv Narayan, Steven M Corsello, David D Peck, Ted E Natoli, Xiaodong Lu, Joshua Gould, John F Davis, Andrew A Tubelli, Jacob K Asiedu, David L Lahr, Jodi E Hirschman, Zihan Liu, Melanie Donahue, Bina Julian, Mariya Khan, David Wadden, Ian C Smith, Daniel Lam, Arthur Liberzon, Courtney Toder, Mukta Bagul, Marek Orzechowski, Oana M Enache, Federica Piccioni, Sarah A Johnson, Nicholas J Lyons, Alice H Berger, Alykhan F Shamji, Angela N Brooks, Anita Vrcic, Corey Flynn, Jacqueline Rosains, David Y Takeda, Roger Hu, Desiree Davison, Justin Lamb, Kristin Ardlie, Larson Hogstrom, Peyton Greenside, Nathanael S Gray, Paul A Clemons, Serena Silver, Xiaoyun Wu, Wen-Ning Zhao, Willis Read-Button, Xiaohua Wu, Stephen J Haggarty, Lucienne V Ronco, Jesse S Boehm, Stuart L Schreiber, John G Doench, Joshua A Bittker, David E Root, Bang Wong, Todd R Golub. A next generation connectivity map: <span>L1000</span> platform and the first 1,000,000 profiles. Cell. 2017;171(6):1437–52. doi:<a href="https://doi.org/10.1016/j.cell.2017.10.049">10.1016/j.cell.2017.10.049</a></div>
</div>
<div id="ref-tsherniak2017depmap" class="csl-entry" role="listitem">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Aviad Tsherniak, Francisca Vazquez, Phil G Montgomery, Barbara A Weir, Gregory Kryukov, Glenn S Cowley, Stanley Gill, William F Harrington, Sasha Pantel, John M Krill-Burger, Robin M Meyers, Levi Ali, Amy Goodale, Yenarae Lee, Guozhi Jiang, Jessica Hsiao, William F J Gerath, Sara Howell, Erin Merkel, Mahmoud Ghandi, Levi A Garraway, David E Root, Todd R Golub, Jesse S Boehm, William C Hahn. Defining a cancer dependency map. Cell. 2017;170(3):564–76. doi:<a href="https://doi.org/10.1016/j.cell.2017.06.010">10.1016/j.cell.2017.06.010</a></div>
</div>
<div id="ref-velickovic2018gat" class="csl-entry" role="listitem">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Petar Veličković, Guillem Cucurull, Arantxa Casanova, Adriana Romero, Pietro Liò, Yoshua Bengio. Graph attention networks. In: International conference on learning representations [Internet]. 2018. Available from: <a href="https://openreview.net/forum?id=rJXMpikCZ">https://openreview.net/forum?id=rJXMpikCZ</a></div>
</div>
<div id="ref-saito2015auprc" class="csl-entry" role="listitem">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Takaya Saito, Marc Rehmsmeier. The precision-recall plot is more informative than the <span>ROC</span> plot when evaluating binary classifiers on imbalanced datasets. PLOS ONE. 2015;10(3):e0118432. doi:<a href="https://doi.org/10.1371/journal.pone.0118432">10.1371/journal.pone.0118432</a></div>
</div>
<div id="ref-wilcoxon1945" class="csl-entry" role="listitem">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Frank Wilcoxon. Individual comparisons by ranking methods. Biometrics Bulletin. 1945;1(6):80–3. doi:<a href="https://doi.org/10.2307/3001968">10.2307/3001968</a></div>
</div>
<div id="ref-holm1979" class="csl-entry" role="listitem">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Sture Holm. A simple sequentially rejective multiple test procedure. Scandinavian Journal of Statistics. 1979;6(2):65–70.</div>
</div>
<div id="ref-seibold2011muc5b" class="csl-entry" role="listitem">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Max A Seibold, Anastasia L Wise, Marcy C Speer, Mark P Steele, Kevin K Brown, James E Loyd, Tasha E Fingerlin, Weimin Zhang, Gunnar Gudmundsson, Steve D Groshong, Christopher M Evans, Stavros Garantziotis, Kenneth B Adler, Burton F Dickey, Roland M du Bois, Ivana V Yang, Ahcene Herron, Dolly Kervitsky, Janet L Talbert, Cheryl Markin, Junesoo Park, Anne L Crews, Susan H Slifer, Scott Auerbach, Michelle G Roy, Jia Lin, Craig E Hennessy, Marvin I Schwarz, David A Schwartz. A common <span>MUC5B</span> promoter polymorphism and pulmonary fibrosis. The New England Journal of Medicine. 2011;364(16):1503–12. doi:<a href="https://doi.org/10.1056/NEJMoa1013660">10.1056/NEJMoa1013660</a></div>
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<!-- GitHub Pages only: article reads + Kokoro listen; site visits go in the footer -->
<div id="gh-toolbar" class="gh-toolbar" hidden="">
  <div id="gh-engagement" class="gh-engagement" aria-live="polite">
    <span class="gh-engagement-item" id="gh-page-stat">
      <span class="gh-engagement-label" id="gh-engagement-label">Article reads</span>
      <span class="gh-engagement-count" id="gh-engagement-count">…</span>
    </span>
  </div>

  <div id="gh-listen" class="gh-listen" hidden="">
    <button type="button" class="gh-listen-btn" id="gh-listen-toggle" aria-pressed="false">
      Listen to this article
    </button>
    <button type="button" class="gh-listen-btn gh-listen-btn-secondary" id="gh-listen-stop" hidden="">
      Stop
    </button>
    <span class="gh-listen-status" id="gh-listen-status" aria-live="polite"></span>
    <audio id="gh-listen-audio" preload="metadata" hidden=""></audio>
  </div>
</div>

<span id="gh-site-stat" class="gh-site-stat" aria-live="polite" hidden="">
  <span class="gh-engagement-label">Site visits</span>
  <span class="gh-engagement-count" id="gh-site-count">…</span>
</span>

<script>
(() => {
  const boot = () => {
    const NAMESPACE = "alanzosportfolio";
    const API = "https://api.counterapi.dev/v1";

    const toolbar = document.getElementById("gh-toolbar");
    const labelEl = document.getElementById("gh-engagement-label");
    const countEl = document.getElementById("gh-engagement-count");
    const siteStat = document.getElementById("gh-site-stat");
    const siteCountEl = document.getElementById("gh-site-count");
    const listenRoot = document.getElementById("gh-listen");
    const listenToggle = document.getElementById("gh-listen-toggle");
    const listenStop = document.getElementById("gh-listen-stop");
    const listenStatus = document.getElementById("gh-listen-status");
    const listenAudio = document.getElementById("gh-listen-audio");

    if (!toolbar || !countEl || !siteStat || !siteCountEl) return;

    const path = (window.location.pathname || "/")
      .replace(/\/index\.html$/, "")
      .replace(/\/+$/, "") || "/";
    const isArticle = /\/articles\/20\d{2}-/.test(path);

    const pageKey = path
      .replace(/^\/portfolio/, "")
      .replace(/^\/+|\/+$/g, "")
      .replace(/\.html$/, "")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() || "home";

    const formatCount = (n) => Number(n).toLocaleString("en-GB");

    const readCounter = async (name, { bump }) => {
      const base = `${API}/${NAMESPACE}/${name}`;
      const urls = bump ? [`${base}/up`, `${base}/`] : [`${base}/`, `${base}`];
      let lastError = null;
      for (const url of urls) {
        try {
          const response = await fetch(url, {
            method: "GET",
            mode: "cors",
            cache: "no-store",
            credentials: "omit",
          });
          if (!response.ok) {
            lastError = new Error(`HTTP ${response.status}`);
            continue;
          }
          const data = await response.json();
          const n = data && (data.count ?? data.value);
          if (n == null) {
            lastError = new Error("missing count");
            continue;
          }
          return Number(n);
        } catch (err) {
          lastError = err;
        }
      }
      throw lastError || new Error("counter failed");
    };

    const bumpOnce = (storageKey) => {
      try {
        if (sessionStorage.getItem(storageKey) === "1") return false;
        sessionStorage.setItem(storageKey, "1");
        return true;
      } catch (_) {
        return true;
      }
    };

    // Site visits: always in the footer (must wait until footer exists).
    const footerHost =
      document.querySelector(".nav-footer-left") ||
      document.querySelector(".nav-footer-center") ||
      document.querySelector("footer.footer .nav-footer") ||
      document.querySelector("footer.footer") ||
      document.querySelector("footer");

    if (footerHost) {
      footerHost.appendChild(siteStat);
      siteStat.hidden = false;
    }

    readCounter("site", { bump: bumpOnce("gh-viewed:site") })
      .then((n) => { siteCountEl.textContent = formatCount(n); })
      .catch(() => { siteCountEl.textContent = "–"; });

    // Article toolbar: reads + listen only on articles.
    if (!isArticle) {
      toolbar.remove();
      return;
    }

    if (labelEl) labelEl.textContent = "Article reads";

    const anchor =
      document.querySelector("header#title-block-header") ||
      document.querySelector(".quarto-title-meta") ||
      document.querySelector("main#quarto-document-content");
    if (anchor && anchor.parentNode) {
      anchor.insertAdjacentElement("afterend", toolbar);
    }
    toolbar.hidden = false;

    readCounter(pageKey, { bump: bumpOnce(`gh-viewed:${pageKey}`) })
      .then((n) => { countEl.textContent = formatCount(n); })
      .catch(() => { countEl.textContent = "–"; });

    if (!listenRoot || !listenToggle || !listenStop || !listenStatus || !listenAudio) return;

    const slugMatch = path.match(/\/articles\/(20\d{2}-[^/]+)/);
    const audioUrl = slugMatch
      ? new URL(`../../gh-audio/${slugMatch[1]}/narration.mp3`, window.location.href).href
      : "";
    if (!audioUrl) return;

    const setIdle = () => {
      listenToggle.textContent = "Listen to this article";
      listenToggle.setAttribute("aria-pressed", "false");
      listenStop.hidden = true;
      listenStatus.textContent = "";
    };

    const setPlaying = () => {
      listenToggle.textContent = "Pause";
      listenToggle.setAttribute("aria-pressed", "true");
      listenStop.hidden = false;
      listenStatus.textContent = "Playing";
    };

    const setPaused = () => {
      listenToggle.textContent = "Resume";
      listenToggle.setAttribute("aria-pressed", "true");
      listenStop.hidden = false;
      listenStatus.textContent = "Paused";
    };

    const stop = () => {
      listenAudio.pause();
      listenAudio.currentTime = 0;
      setIdle();
    };

    fetch(audioUrl, { method: "HEAD", cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error("missing audio");
        listenAudio.src = audioUrl;
        listenRoot.hidden = false;
        setIdle();
      })
      .catch(() => {
        listenRoot.hidden = true;
      });

    listenAudio.addEventListener("play", setPlaying);
    listenAudio.addEventListener("playing", setPlaying);
    listenAudio.addEventListener("pause", () => {
      if (!listenAudio.ended && listenAudio.currentTime > 0) setPaused();
    });
    listenAudio.addEventListener("ended", setIdle);
    listenAudio.addEventListener("error", () => {
      listenStatus.textContent = "Audio could not be loaded.";
      setIdle();
    });

    listenToggle.addEventListener("click", async () => {
      if (listenAudio.paused) {
        try {
          await listenAudio.play();
        } catch (_) {
          listenStatus.textContent = "Playback was blocked by the browser.";
        }
        return;
      }
      listenAudio.pause();
    });

    listenStop.addEventListener("click", stop);
    window.addEventListener("beforeunload", stop);
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//(?:andreslanzos\.quarto\.pub|alanzos\.github\.io)(?:/|$)");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="dark">
<input type="hidden" id="giscus-alt-theme" value="light">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "alanzos/portfolio";
    script.dataset.repoId = "R_kgDOI50biQ";
    script.dataset.category = "General";
    script.dataset.categoryId = "DIC_kwDOI50bic4DCqaX";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Andres Lanzos · Basel, Switzerland</p>
</div>   
    <div class="nav-footer-center">
<p><a href="mailto:andreslanzos@gmail.com">andreslanzos@gmail.com</a></p>
</div>
    <div class="nav-footer-right">
<p><a href="https://buttondown.com/andreslanzos">Subscribe to my articles</a> · <a href="https://www.linkedin.com/in/andreslanzos/">LinkedIn</a> · <a href="https://github.com/alanzos">GitHub</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>