<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-09">
<meta name="description" content="The most famous biological age clocks can all return an age in years. But those years do not mean the same thing.">

<title>What does it mean to be 5 biological years older? – Andres Lanzos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../jpg/photo.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-703069f40e948ba70f3f3e6eba71fad1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-fc15bee6fe409d5dc7e34485bd7b8a48.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;0,8..60,700;1,8..60,400;1,8..60,500&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="What does it mean to be 5 biological years older? – Andres Lanzos">
<meta property="og:description" content="The most famous biological age clocks can all return an age in years. But those years do not mean the same thing.">
<meta property="og:image" content="https://alanzos.github.io/portfolio/articles/2026-08-09-biological-age-gap/image.png">
<meta property="og:site_name" content="Andres Lanzos">
<meta property="og:image:height" content="2700">
<meta property="og:image:width" content="2160">
<meta property="og:image:alt" content="Infographic comparing what a +5 year age gap means across KDM, Phenotypic Age, Horvath, Hannum, DNAm PhenoAge, and GrimAge">
<meta name="twitter:title" content="What does it mean to be 5 biological years older? – Andres Lanzos">
<meta name="twitter:description" content="The most famous biological age clocks can all return an age in years. But those years do not mean the same thing.">
<meta name="twitter:image" content="https://alanzos.github.io/portfolio/articles/2026-08-09-biological-age-gap/image.png">
<meta name="twitter:image-height" content="2700">
<meta name="twitter:image-width" content="2160">
<meta name="twitter:image:alt" content="Infographic comparing what a +5 year age gap means across KDM, Phenotypic Age, Horvath, Hannum, DNAm PhenoAge, and GrimAge">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Andres Lanzos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../articles/index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../articles/index.xml"> <i class="bi bi-rss" role="img" aria-label="Articles RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:andreslanzos@gmail.com"> <i class="bi bi-envelope" role="img" aria-label="Email Andres Lanzos">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/andreslanzos/"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn profile">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/alanzos"> <i class="bi bi-github" role="img" aria-label="GitHub profile">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#kdm-biological-age-what-age-normally-has-physiology-like-mine" id="toc-kdm-biological-age-what-age-normally-has-physiology-like-mine" class="nav-link" data-scroll-target="#kdm-biological-age-what-age-normally-has-physiology-like-mine">1. KDM Biological Age: “What age normally has physiology like mine?”</a></li>
  <li><a href="#phenotypic-age-what-age-normally-has-my-mortality-risk" id="toc-phenotypic-age-what-age-normally-has-my-mortality-risk" class="nav-link" data-scroll-target="#phenotypic-age-what-age-normally-has-my-mortality-risk">2. Phenotypic Age: “What age normally has my mortality risk?”</a></li>
  <li><a href="#horvath-clock-how-old-does-my-dna-methylation-pattern-look" id="toc-horvath-clock-how-old-does-my-dna-methylation-pattern-look" class="nav-link" data-scroll-target="#horvath-clock-how-old-does-my-dna-methylation-pattern-look">3. Horvath clock: “How old does my DNA methylation pattern look?”</a></li>
  <li><a href="#hannum-clock-how-old-does-my-blood-methylation-look" id="toc-hannum-clock-how-old-does-my-blood-methylation-look" class="nav-link" data-scroll-target="#hannum-clock-how-old-does-my-blood-methylation-look">4. Hannum clock: “How old does my blood methylation look?”</a></li>
  <li><a href="#dnam-phenoage-putting-phenotypic-age-into-dna-methylation" id="toc-dnam-phenoage-putting-phenotypic-age-into-dna-methylation" class="nav-link" data-scroll-target="#dnam-phenoage-putting-phenotypic-age-into-dna-methylation">5. DNAm PhenoAge: putting Phenotypic Age into DNA methylation</a></li>
  <li><a href="#grimage-how-old-does-my-mortality-related-methylation-profile-look" id="toc-grimage-how-old-does-my-mortality-related-methylation-profile-look" class="nav-link" data-scroll-target="#grimage-how-old-does-my-mortality-related-methylation-profile-look">6. GrimAge: “How old does my mortality-related methylation profile look?”</a></li>
  <li><a href="#so-what-does-5-biological-years-actually-mean" id="toc-so-what-does-5-biological-years-actually-mean" class="nav-link" data-scroll-target="#so-what-does-5-biological-years-actually-mean">So what does “+5 biological years” actually mean?</a></li>
  <li><a href="#the-most-important-source-of-bias-what-was-the-clock-trained-to-predict" id="toc-the-most-important-source-of-bias-what-was-the-clock-trained-to-predict" class="nav-link" data-scroll-target="#the-most-important-source-of-bias-what-was-the-clock-trained-to-predict">The most important source of bias: what was the clock trained to predict?</a></li>
  <li><a href="#raw-age-gap-or-adjusted-age-gap" id="toc-raw-age-gap-or-adjusted-age-gap" class="nav-link" data-scroll-target="#raw-age-gap-or-adjusted-age-gap">Raw age gap or adjusted age gap?</a></li>
  <li><a href="#there-is-no-single-best-biological-age-clock" id="toc-there-is-no-single-best-biological-age-clock" class="nav-link" data-scroll-target="#there-is-no-single-best-biological-age-clock">There is no single “best” biological age clock</a></li>
  <li><a href="#one-thing-that-is-not-an-age-gap-clock" id="toc-one-thing-that-is-not-an-age-gap-clock" class="nav-link" data-scroll-target="#one-thing-that-is-not-an-age-gap-clock">One thing that is not an age-gap clock</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">What does it mean to be 5 biological years older?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Ageing</div>
    <div class="quarto-category">Biomarkers</div>
  </div>
  </div>

<div>
  <div class="description">
    The most famous biological age clocks can all return an age in years. But those years do not mean the same thing.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="tldr">
<p><strong>TLDR.</strong> Biological age clocks can produce surprisingly similar-looking results - 48 years, 55 years, +6 years - while measuring very different things. Some estimate the age at which your physiology would be typical. Some predict chronological age from DNA methylation. Others convert mortality-related information into an age scale. Before interpreting an age gap, you need to know what the clock was trained to predict.</p>
</div>
<p>In a <a href="../2026-08-01-age-acceleration/">previous note</a>, I argued that many “age acceleration” scores are really age gaps: the difference between a clock age and chronological age, or a residual after adjusting clock age for chronological age.</p>
<p>This follow-up asks a more practical question: if two people are both chronologically 50, and one clock returns 45 while another returns 55, what do those five-year gaps actually mean?</p>
<p>Imagine two people.</p>
<p>Both are chronologically 50 years old.</p>
<p>A biological age clock gives one of them an estimated age of 45 and the other an estimated age of 55.</p>
<p>The obvious calculation is:</p>
<p>Age gap = estimated biological age − chronological age</p>
<p>So their age gaps are:</p>
<p>45 − 50 = −5</p>
<p>and</p>
<p>55 − 50 = +5</p>
<p>The first person appears five years younger. The second appears five years older.</p>
<p>Simple.</p>
<p>Except for one important problem:</p>
<p><strong>five biological years does not mean the same thing in every clock.</strong></p>
<p>A +5-year Horvath age gap, a +5-year Phenotypic Age gap and a +5-year GrimAge gap are not three independent measurements of the same biological quantity.</p>
<p>They use different inputs.</p>
<p>They were trained against different targets.</p>
<p>And the resulting number represents something different.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image.png" class="img-fluid figure-img" alt="Infographic comparing what a +5 year age gap means across KDM, Phenotypic Age, Horvath, Hannum, DNAm PhenoAge, and GrimAge"></p>
<figcaption>What does +5 biological years mean across major age-gap clocks?</figcaption>
</figure>
</div>
<p>Here are the major age-gap clocks and what their numbers actually mean.</p>
<section id="at-a-glance" class="level2">
<h2 class="anchored" data-anchor-id="at-a-glance">At a glance</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Clock</th>
<th>What you need</th>
<th>What it returns</th>
<th>What the age represents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>KDM Biological Age</strong></td>
<td>Age + physiological/clinical biomarkers</td>
<td>Age in years</td>
<td>Age at which your physiological profile would be typical in the reference population</td>
</tr>
<tr class="even">
<td><strong>Phenotypic Age</strong></td>
<td>Age + 9 routine blood biomarkers</td>
<td>Age in years</td>
<td>Age associated with your estimated mortality risk</td>
</tr>
<tr class="odd">
<td><strong>Horvath clock</strong></td>
<td>DNA methylation, 353 CpGs</td>
<td>DNAm age in years</td>
<td>Age predicted from methylation patterns across tissues</td>
</tr>
<tr class="even">
<td><strong>Hannum clock</strong></td>
<td>Blood DNA methylation, 71 CpGs</td>
<td>DNAm age in years</td>
<td>Age predicted from blood methylation patterns</td>
</tr>
<tr class="odd">
<td><strong>DNAm PhenoAge</strong></td>
<td>Blood DNA methylation, 513 CpGs</td>
<td>Age in years</td>
<td>DNA-methylation estimate of Phenotypic Age</td>
</tr>
<tr class="even">
<td><strong>GrimAge</strong></td>
<td>Blood DNA methylation + age + sex</td>
<td>Age in years</td>
<td>Mortality-oriented methylation score transformed onto an age scale</td>
</tr>
</tbody>
</table>
<p>The important column is the last one.</p>
<p>That is what determines what an age gap actually means.</p>
</section>
<section id="kdm-biological-age-what-age-normally-has-physiology-like-mine" class="level2">
<h2 class="anchored" data-anchor-id="kdm-biological-age-what-age-normally-has-physiology-like-mine">1. KDM Biological Age: “What age normally has physiology like mine?”</h2>
<p>One of the classic approaches is the <strong>Klemera–Doubal Method</strong>, or KDM.</p>
<p>Unlike a single fixed clock, KDM is really a statistical framework: researchers choose physiological biomarkers that change systematically with chronological age, learn their age trajectories in a reference population, and combine them to estimate biological age.</p>
<p>A widely used implementation developed from NHANES III data by Morgan Levine used chronological age together with 10 measurements [8]:</p>
<ul>
<li>albumin</li>
<li>alkaline phosphatase</li>
<li>blood urea nitrogen</li>
<li>creatinine</li>
<li>C-reactive protein</li>
<li>cytomegalovirus optical density</li>
<li>HbA1c</li>
<li>total cholesterol</li>
<li>systolic blood pressure</li>
<li>forced expiratory volume in one second, or FEV₁</li>
</ul>
<p>Other implementations use somewhat different panels, which is important: <strong>“KDM Biological Age” does not always mean exactly the same biomarker set.</strong> [1]</p>
<section id="what-does-the-number-mean" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean">What does the number mean?</h3>
<p>KDM can be thought of as asking:</p>
<p><strong>At what chronological age would this combination of physiological measurements be typical in the reference population?</strong></p>
<p>If you are 50 and KDM gives you a biological age of 55, the interpretation is approximately:</p>
<p><strong>your physiological profile resembles the average profile associated with someone around 55 in the reference population.</strong></p>
<p>That is much more precise than saying:</p>
<blockquote class="blockquote">
<p>“Your body is literally five years older.”</p>
</blockquote>
<p>It is not.</p>
<p>It is a statistical position on a physiological ageing trajectory. [2]</p>
</section>
<section id="the-main-biases" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases">The main biases</h3>
<p>The biggest limitation is <strong>reference-population dependence</strong>.</p>
<p>The relationship between blood pressure, lung function, blood biomarkers and age is estimated from a particular population. Change the population, historical period or biomarker panel and the biological-age estimate can change. Modern KDM implementations consequently use several different panels. [1]</p>
<p>Chronological age itself is also incorporated into common implementations. Therefore, KDM is not an age-independent reading of physiology.</p>
<p>And because it is based on physiological measurements, medical conditions, medication, inflammation and other transient or chronic processes can influence the result. That is partly the point of the clock, but it also means the number should not be interpreted as a direct measurement of some universal underlying “true age”.</p>
</section>
</section>
<section id="phenotypic-age-what-age-normally-has-my-mortality-risk" class="level2">
<h2 class="anchored" data-anchor-id="phenotypic-age-what-age-normally-has-my-mortality-risk">2. Phenotypic Age: “What age normally has my mortality risk?”</h2>
<p><strong>Phenotypic Age</strong>, often shortened to PhenoAge, looks superficially similar to KDM.</p>
<p>But its training target is fundamentally different.</p>
<p>It was constructed from chronological age plus nine clinical biomarkers:</p>
<ul>
<li>albumin</li>
<li>creatinine</li>
<li>glucose</li>
<li>C-reactive protein</li>
<li>lymphocyte percentage</li>
<li>mean corpuscular volume</li>
<li>red-cell distribution width</li>
<li>alkaline phosphatase</li>
<li>white-blood-cell count</li>
</ul>
<p>The researchers started with a larger set of clinical variables and selected these biomarkers using mortality modelling in NHANES III. The resulting mortality estimate was then converted back into units of years. [3]</p>
<p>That last step is crucial.</p>
<section id="what-does-the-number-mean-1" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean-1">What does the number mean?</h3>
<p>Phenotypic Age is approximately a <strong>mortality-risk-equivalent age</strong>.</p>
<p>Suppose you are 50 and your Phenotypic Age is 55.</p>
<p>The intended interpretation is:</p>
<p><strong>your estimated mortality risk corresponds to the average mortality risk associated with a 55-year-old in the reference population.</strong></p>
<p>That interpretation comes directly from the construction of the clock. [3]</p>
<p>It does <strong>not</strong> mean:</p>
<ul>
<li>your organs are literally 55;</li>
<li>every biological system has aged five extra years;</li>
<li>you have lost five years of life expectancy;</li>
<li>or you have been ageing faster throughout your life.</li>
</ul>
<p>Those are different claims.</p>
</section>
<section id="the-main-biases-1" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases-1">The main biases</h3>
<p>Phenotypic Age includes chronological age as an input. So part of a person’s Phenotypic Age is deliberately anchored to birthday age. [3]</p>
<p>It is also sensitive to the physiology represented by its biomarkers. CRP and white-blood-cell count, for example, contain inflammatory and immune information; creatinine reflects renal physiology; glucose reflects metabolic state.</p>
<p>Another particularly important bias was visible in the original validation: younger adults tended to receive somewhat overestimated Phenotypic Ages, while older adults tended to receive underestimated values. The researchers therefore defined <strong>PhenoAgeAccel</strong> as the residual after regressing Phenotypic Age on chronological age. [3]</p>
<p>So there are actually two possible numbers:</p>
<p>raw gap = Phenotypic Age − chronological age</p>
<p>and an age-adjusted residual:</p>
<p>PhenoAgeAccel = Phenotypic Age − E(Phenotypic Age | age)</p>
<p>For research comparisons, the second can be preferable because it corrects systematic age-related calibration.</p>
</section>
</section>
<section id="horvath-clock-how-old-does-my-dna-methylation-pattern-look" class="level2">
<h2 class="anchored" data-anchor-id="horvath-clock-how-old-does-my-dna-methylation-pattern-look">3. Horvath clock: “How old does my DNA methylation pattern look?”</h2>
<p>In 2013, Steve Horvath introduced what became probably the best-known epigenetic clock.</p>
<p>Instead of clinical blood chemistry, the clock looks at <strong>DNA methylation</strong>.</p>
<p>The model was trained using around 8,000 samples from 82 datasets containing 51 healthy tissue and cell types. Elastic-net regression selected <strong>353 CpG sites</strong> whose weighted methylation pattern predicts chronological age. [4]</p>
<section id="what-does-it-require" class="level3">
<h3 class="anchored" data-anchor-id="what-does-it-require">What does it require?</h3>
<p>DNA from which methylation at the relevant CpG sites can be measured, generally through a methylation-array experiment.</p>
<p>Unlike Hannum’s clock, the major advantage of Horvath’s original clock was that it was designed as a <strong>multi-tissue</strong> predictor rather than exclusively as a blood clock. [4]</p>
</section>
<section id="what-does-the-number-mean-2" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean-2">What does the number mean?</h3>
<p>Suppose you are 50 and your Horvath DNAm age is 55.</p>
<p>The safest interpretation is:</p>
<p><strong>your methylation pattern at the clock’s 353 CpGs resembles the pattern that the model associates with approximately age 55.</strong></p>
<p>Your raw epigenetic age gap is therefore:</p>
<p>55 − 50 = +5 years</p>
<p>But this is fundamentally different from Phenotypic Age.</p>
<p>Horvath’s original clock was trained primarily to <strong>predict chronological age</strong>.</p>
<p>Phenotypic Age was trained around mortality.</p>
<p>Therefore, +5 Horvath years do not mean that you have the mortality risk of someone five years older. [4]</p>
<p>They mean that your methylation clock is advanced relative to your chronological age.</p>
</section>
<section id="the-main-biases-2" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases-2">The main biases</h3>
<p>That training objective creates an important limitation.</p>
<p>A clock can be extremely good at predicting chronological age without necessarily being the best predictor of disease, mortality or physiological decline. Chronological-age prediction and health-risk prediction are related questions, but they are not identical.</p>
<p>Methylation estimates can also depend on tissue, cell composition, population characteristics and preprocessing. Horvath’s clock was deliberately trained across many tissues, which makes it unusually portable, but accuracy is not identical across every tissue or population. [4]</p>
<p>And, as with other age-prediction models, regression toward the population mean can affect the raw age gap.</p>
</section>
</section>
<section id="hannum-clock-how-old-does-my-blood-methylation-look" class="level2">
<h2 class="anchored" data-anchor-id="hannum-clock-how-old-does-my-blood-methylation-look">4. Hannum clock: “How old does my blood methylation look?”</h2>
<p>The <strong>Hannum clock</strong> appeared at almost the same time as Horvath’s.</p>
<p>The original study analysed whole-blood methylation from 656 people aged 19–101 and developed a model centred on <strong>71 methylation markers</strong> that strongly predicted chronological age. [5]</p>
<p>The conceptual difference from Horvath is straightforward:</p>
<p><strong>Hannum is fundamentally a blood-derived clock.</strong></p>
<p>Horvath was designed as a pan-tissue clock.</p>
<section id="what-does-the-number-mean-3" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean-3">What does the number mean?</h3>
<p>For a 50-year-old with a Hannum age of 55:</p>
<p><strong>the person’s blood DNA-methylation pattern looks approximately five years older than expected from chronological age.</strong></p>
<p>Again, this is a molecular age-prediction gap.</p>
<p>It is not directly a five-year difference in mortality risk or life expectancy.</p>
</section>
<section id="the-main-biases-3" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases-3">The main biases</h3>
<p>Because it was developed in whole blood, blood-cell composition matters.</p>
<p>The proportions of different immune-cell types change with age and health. Some of that information may itself be biologically meaningful, but it means that the Hannum gap can reflect changes in the cellular composition of blood as well as methylation changes occurring within individual cell types.</p>
<p>The original development population was also much narrower than a globally representative population, consisting primarily of Caucasian and Hispanic participants. [5]</p>
<p>And like Horvath, Hannum is a <strong>first-generation chronological-age clock</strong>.</p>
<p>Its +5 years primarily means “older-looking methylation”, not “five years greater mortality-equivalent age”.</p>
</section>
</section>
<section id="dnam-phenoage-putting-phenotypic-age-into-dna-methylation" class="level2">
<h2 class="anchored" data-anchor-id="dnam-phenoage-putting-phenotypic-age-into-dna-methylation">5. DNAm PhenoAge: putting Phenotypic Age into DNA methylation</h2>
<p>Then researchers started doing something different.</p>
<p>Instead of asking DNA methylation to predict chronological age, why not ask it to predict a biological phenotype associated with health and mortality?</p>
<p>That produced <strong>DNAm PhenoAge</strong>.</p>
<p>Its development happened in two stages.</p>
<p>First, the clinical Phenotypic Age measure was constructed from chronological age and the nine clinical biomarkers discussed earlier.</p>
<p>Then researchers used blood DNA methylation to predict that Phenotypic Age.</p>
<p>Elastic-net regression selected <strong>513 CpG sites</strong>. [6]</p>
<section id="what-does-the-number-mean-4" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean-4">What does the number mean?</h3>
<p>This distinction is subtle but extremely important.</p>
<p>If you are 50 and your DNAm PhenoAge is 55, it does not mean exactly the same thing as having a clinical Phenotypic Age of 55.</p>
<p>Instead:</p>
<p><strong>your DNA-methylation profile produces a predicted Phenotypic Age of approximately 55 according to the methylation model.</strong></p>
<p>It is a molecular proxy for a clinical mortality-oriented ageing phenotype. [6]</p>
<p>That makes DNAm PhenoAge a kind of second-generation epigenetic clock.</p>
<p>Horvath:</p>
<p>DNA methylation → chronological age</p>
<p>DNAm PhenoAge:</p>
<p>DNA methylation → Phenotypic Age</p>
<p>The target changed.</p>
<p>And therefore the meaning of the age gap changed too.</p>
</section>
<section id="the-main-biases-4" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases-4">The main biases</h3>
<p>DNAm PhenoAge inherits limitations from <strong>both layers</strong> of this process.</p>
<p>The underlying Phenotypic Age target comes from a particular clinical and mortality model.</p>
<p>The methylation clock then learns a proxy for that target.</p>
<p>So the final number is one step removed from the actual clinical biomarkers used to construct Phenotypic Age.</p>
<p>It is also affected by the usual considerations surrounding blood methylation assays, cell composition, cohort differences and technical processing.</p>
<p>Its advantage is precisely the same thing as its limitation: it compresses a much more complicated biological and epidemiological construct into a single blood-DNA measurement. [6]</p>
</section>
</section>
<section id="grimage-how-old-does-my-mortality-related-methylation-profile-look" class="level2">
<h2 class="anchored" data-anchor-id="grimage-how-old-does-my-mortality-related-methylation-profile-look">6. GrimAge: “How old does my mortality-related methylation profile look?”</h2>
<p><strong>GrimAge</strong> pushes the idea even further toward health outcomes.</p>
<p>Its developers first created DNA-methylation surrogates for smoking exposure and several plasma proteins.</p>
<p>The final original GrimAge model combines:</p>
<ul>
<li>chronological age</li>
<li>sex</li>
<li>a DNAm estimate of smoking pack-years</li>
<li>DNAm surrogates for seven plasma proteins:
<ul>
<li>adrenomedullin</li>
<li>beta-2-microglobulin</li>
<li>cystatin C</li>
<li>GDF-15</li>
<li>leptin</li>
<li>PAI-1</li>
<li>TIMP-1</li>
</ul></li>
</ul>
<p>The methylation surrogates collectively use 1,030 unique CpGs. These variables were then combined using mortality data, and the resulting mortality predictor was transformed into units of years. [7]</p>
<p>Importantly, a person does <strong>not</strong> need to measure those seven proteins individually to calculate DNAm GrimAge. They are estimated from the person’s blood DNA-methylation profile. [7]</p>
<section id="what-does-the-number-mean-5" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-number-mean-5">What does the number mean?</h3>
<p>This is where interpreting the raw age becomes dangerous.</p>
<p>Suppose you are 50 and GrimAge gives 55.</p>
<p>That means your mortality-related methylation composite has been mapped to an age-like value of 55.</p>
<p>But researchers usually focus on <strong>AgeAccelGrim</strong>, which adjusts GrimAge for chronological age. [7]</p>
<p>So a +5 AgeAccelGrim is better interpreted as:</p>
<p><strong>your GrimAge score is five years higher than expected for someone of your chronological age.</strong></p>
<p>It does <strong>not</strong> mean:</p>
<p><strong>you will die five years earlier.</strong></p>
<p>GrimAge is associated with mortality and multiple age-related outcomes, but its “years” are the scale of a statistical mortality-related biomarker, not a countdown timer. [7]</p>
</section>
<section id="the-main-biases-5" class="level3">
<h3 class="anchored" data-anchor-id="the-main-biases-5">The main biases</h3>
<p>GrimAge is deliberately sensitive to things associated with mortality.</p>
<p>Smoking is the clearest example: a DNA-methylation estimate of cumulative smoking exposure is built directly into the model. [7]</p>
<p>That is a feature if your aim is to predict mortality risk.</p>
<p>But it also means that GrimAge should not automatically be interpreted as a pure measurement of an intrinsic biological ageing mechanism.</p>
<p>A heavy smoking history can make GrimAge substantially worse because the clock was explicitly designed to contain that information.</p>
<p>Chronological age and sex are also model inputs.</p>
<p>Again, the clock is doing what it was built to do.</p>
<p>The error comes when we interpret its output as something it was never built to measure.</p>
</section>
</section>
<section id="so-what-does-5-biological-years-actually-mean" class="level2">
<h2 class="anchored" data-anchor-id="so-what-does-5-biological-years-actually-mean">So what does “+5 biological years” actually mean?</h2>
<p>This is the comparison I find most useful.</p>
<p>If a 50-year-old receives a result of 55:</p>
<section id="kdm-5-years" class="level3">
<h3 class="anchored" data-anchor-id="kdm-5-years">KDM: +5 years</h3>
<p><strong>“My combined physiological measurements resemble those normally observed at an older age in the reference population.”</strong></p>
</section>
<section id="phenotypic-age-5-years" class="level3">
<h3 class="anchored" data-anchor-id="phenotypic-age-5-years">Phenotypic Age: +5 years</h3>
<p><strong>“My clinical biomarker profile corresponds to the mortality risk associated with someone approximately five years older in the reference population.”</strong></p>
</section>
<section id="horvath-5-years" class="level3">
<h3 class="anchored" data-anchor-id="horvath-5-years">Horvath: +5 years</h3>
<p><strong>“My DNA-methylation pattern looks approximately five years older than my chronological age according to a pan-tissue chronological-age predictor.”</strong></p>
</section>
<section id="hannum-5-years" class="level3">
<h3 class="anchored" data-anchor-id="hannum-5-years">Hannum: +5 years</h3>
<p><strong>“My blood DNA-methylation pattern looks approximately five years older according to a blood-trained chronological-age predictor.”</strong></p>
</section>
<section id="dnam-phenoage-5-years" class="level3">
<h3 class="anchored" data-anchor-id="dnam-phenoage-5-years">DNAm PhenoAge: +5 years</h3>
<p><strong>“My blood DNA-methylation profile predicts a Phenotypic Age approximately five years above my chronological age.”</strong></p>
</section>
<section id="grimage-5-years" class="level3">
<h3 class="anchored" data-anchor-id="grimage-5-years">GrimAge: +5 years</h3>
<p>More carefully, when using AgeAccelGrim:</p>
<p><strong>“My mortality-oriented methylation score is approximately five years above what the model expects at my chronological age.”</strong></p>
<p>Those statements sound similar.</p>
<p>Scientifically, they are very different.</p>
</section>
</section>
<section id="the-most-important-source-of-bias-what-was-the-clock-trained-to-predict" class="level2">
<h2 class="anchored" data-anchor-id="the-most-important-source-of-bias-what-was-the-clock-trained-to-predict">The most important source of bias: what was the clock trained to predict?</h2>
<p>We often focus on whether a clock uses blood, DNA, hundreds of CpGs or ten clinical variables.</p>
<p>But perhaps the more important question is:</p>
<p><strong>What was the target?</strong></p>
<p>For the original Horvath and Hannum clocks, the target was primarily:</p>
<p>chronological age</p>
<p>For KDM, the aim is closer to:</p>
<p>age-associated physiology</p>
<p>For Phenotypic Age:</p>
<p>mortality-risk-equivalent age</p>
<p>For DNAm PhenoAge:</p>
<p>methylation-predicted Phenotypic Age</p>
<p>And for GrimAge:</p>
<p>mortality-related information expressed on an age scale</p>
<p>This is why comparing clocks solely by asking which one produces the smallest error against chronological age can be misleading.</p>
<p>If the clock was deliberately designed to identify people of the same chronological age who have different mortality risks, deviation from chronological age is not necessarily a mistake.</p>
<p>It may be the information we wanted the clock to find. [3]</p>
</section>
<section id="raw-age-gap-or-adjusted-age-gap" class="level2">
<h2 class="anchored" data-anchor-id="raw-age-gap-or-adjusted-age-gap">Raw age gap or adjusted age gap?</h2>
<p>There is one final complication.</p>
<p>The simplest calculation is:</p>
<p>raw age gap = clock age − chronological age</p>
<p>That is intuitive and useful for explaining a result.</p>
<p>But many clocks show systematic age bias. Young people may be predicted slightly too old, while old people may be predicted slightly too young.</p>
<p>Phenotypic Age showed exactly this pattern in its validation data. [3]</p>
<p>Researchers therefore frequently calculate an age-adjusted residual:</p>
<p>adjusted age gap = clock age − E(clock age | chronological age)</p>
<p>This asks a subtly different question:</p>
<p><strong>How unusual is my clock value compared with other people of my age?</strong></p>
<p>For scientific comparisons, that can be much more informative.</p>
<p>It also means that when somebody says their “age acceleration is +5 years”, the first question should be:</p>
<p><strong>+5 according to which clock, and calculated how?</strong></p>
<p>Without those two pieces of information, the number is almost meaningless.</p>
</section>
<section id="there-is-no-single-best-biological-age-clock" class="level2">
<h2 class="anchored" data-anchor-id="there-is-no-single-best-biological-age-clock">There is no single “best” biological age clock</h2>
<p>Different clocks answer different questions.</p>
<p>If I wanted a relatively accessible measure based on routine clinical blood tests, <strong>Phenotypic Age</strong> is particularly attractive.</p>
<p>If I wanted to ask where someone’s overall physiology lies relative to age-associated population trajectories, <strong>KDM</strong> answers a slightly different question.</p>
<p>If I wanted a molecular measure of age-related DNA methylation across tissues, the <strong>Horvath clock</strong> is historically fundamental.</p>
<p>If I wanted a blood-specific first-generation methylation age, <strong>Hannum</strong> is another classic.</p>
<p>If I wanted DNA methylation tied more closely to physiological ageing, <strong>DNAm PhenoAge</strong> changes the target.</p>
<p>And if prediction of mortality-related outcomes were the priority, <strong>GrimAge</strong> was explicitly built much closer to that objective. [4]</p>
<p>None measures an individual’s one true biological age.</p>
<p>They are models.</p>
<p>Each compresses a particular collection of biological observations into an age-like number.</p>
<p>The question is therefore not simply:</p>
<p><strong>“What is my biological age?”</strong></p>
<p>A better question is:</p>
<p><strong>“According to this particular model, what does my biology look older or younger with respect to?”</strong></p>
<p>Once you ask that, an age gap becomes much easier to interpret.</p>
</section>
<section id="one-thing-that-is-not-an-age-gap-clock" class="level2">
<h2 class="anchored" data-anchor-id="one-thing-that-is-not-an-age-gap-clock">One thing that is not an age-gap clock</h2>
<p>This distinction also explains why a measure such as <strong>DunedinPACE</strong> does not belong in the table above.</p>
<p>DunedinPACE returns a <strong>pace</strong>, approximately biological years of physiological change per chronological year.</p>
<p>A result around 1.0 is a rate.</p>
<p>It is not an age.</p>
<p>Therefore:</p>
<p>DunedinPACE − chronological age</p>
<p>has no meaningful interpretation.</p>
<p>That is a different family of ageing measure entirely.</p>
<p>And that difference - between <strong>how old you appear now</strong> and <strong>how quickly you are changing over time</strong> - is where I will go next.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC8602613/">Kwon D, Belsky DW. A toolkit for quantification of biological age from blood chemistry and organ function test data: BioAge.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10307789/">Mak JKL. et al.&nbsp;Clinical biomarker-based biological aging and risk of cancer in the UK Biobank.</a></li>
<li><a href="https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002718">Liu Z. et al.&nbsp;A new aging measure captures morbidity and mortality risk across diverse subpopulations from NHANES IV.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4015143/">Horvath S. DNA methylation age of human tissues and cell types.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3780611/">Hannum G. et al.&nbsp;Genome-wide Methylation Profiles Reveal Quantitative Views of Human Aging Rates.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5940111/">Levine ME. et al.&nbsp;An epigenetic biomarker of aging for lifespan and healthspan.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6366976/">Lu AT. et al.&nbsp;DNA methylation GrimAge strongly predicts lifespan and healthspan.</a></li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3660119/">Levine ME. Modeling the Rate of Senescence: Can Estimated Biological Age Predict Mortality More Accurately Than Chronological Age?</a></li>
</ol>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<!-- GitHub Pages only: article reads + Kokoro listen; site visits go in the footer -->
<div id="gh-toolbar" class="gh-toolbar" hidden="">
  <div id="gh-engagement" class="gh-engagement" aria-live="polite">
    <span class="gh-engagement-item" id="gh-page-stat">
      <span class="gh-engagement-label" id="gh-engagement-label">Article reads</span>
      <span class="gh-engagement-count" id="gh-engagement-count">…</span>
    </span>
  </div>

  <div id="gh-listen" class="gh-listen" hidden="">
    <button type="button" class="gh-listen-btn" id="gh-listen-toggle" aria-pressed="false">
      Listen to this article
    </button>
    <button type="button" class="gh-listen-btn gh-listen-btn-secondary" id="gh-listen-stop" hidden="">
      Stop
    </button>
    <span class="gh-listen-status" id="gh-listen-status" aria-live="polite"></span>
    <audio id="gh-listen-audio" preload="metadata" hidden=""></audio>
  </div>
</div>

<span id="gh-site-stat" class="gh-site-stat" aria-live="polite" hidden="">
  <span class="gh-engagement-label">Site visits</span>
  <span class="gh-engagement-count" id="gh-site-count">…</span>
</span>

<script>
(() => {
  const boot = () => {
    const NAMESPACE = "alanzosportfolio";
    const API = "https://api.counterapi.dev/v1";

    const toolbar = document.getElementById("gh-toolbar");
    const labelEl = document.getElementById("gh-engagement-label");
    const countEl = document.getElementById("gh-engagement-count");
    const siteStat = document.getElementById("gh-site-stat");
    const siteCountEl = document.getElementById("gh-site-count");
    const listenRoot = document.getElementById("gh-listen");
    const listenToggle = document.getElementById("gh-listen-toggle");
    const listenStop = document.getElementById("gh-listen-stop");
    const listenStatus = document.getElementById("gh-listen-status");
    const listenAudio = document.getElementById("gh-listen-audio");

    if (!toolbar || !countEl || !siteStat || !siteCountEl) return;

    const path = (window.location.pathname || "/")
      .replace(/\/index\.html$/, "")
      .replace(/\/+$/, "") || "/";
    const isArticle = /\/articles\/20\d{2}-/.test(path);

    const pageKey = path
      .replace(/^\/portfolio/, "")
      .replace(/^\/+|\/+$/g, "")
      .replace(/\.html$/, "")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() || "home";

    const formatCount = (n) => Number(n).toLocaleString("en-GB");

    const readCounter = async (name, { bump }) => {
      const base = `${API}/${NAMESPACE}/${name}`;
      const urls = bump ? [`${base}/up`, `${base}/`] : [`${base}/`, `${base}`];
      let lastError = null;
      for (const url of urls) {
        try {
          const response = await fetch(url, {
            method: "GET",
            mode: "cors",
            cache: "no-store",
            credentials: "omit",
          });
          if (!response.ok) {
            lastError = new Error(`HTTP ${response.status}`);
            continue;
          }
          const data = await response.json();
          const n = data && (data.count ?? data.value);
          if (n == null) {
            lastError = new Error("missing count");
            continue;
          }
          return Number(n);
        } catch (err) {
          lastError = err;
        }
      }
      throw lastError || new Error("counter failed");
    };

    const bumpOnce = (storageKey) => {
      try {
        if (sessionStorage.getItem(storageKey) === "1") return false;
        sessionStorage.setItem(storageKey, "1");
        return true;
      } catch (_) {
        return true;
      }
    };

    // Site visits: always in the footer (must wait until footer exists).
    const footerHost =
      document.querySelector(".nav-footer-left") ||
      document.querySelector(".nav-footer-center") ||
      document.querySelector("footer.footer .nav-footer") ||
      document.querySelector("footer.footer") ||
      document.querySelector("footer");

    if (footerHost) {
      footerHost.appendChild(siteStat);
      siteStat.hidden = false;
    }

    readCounter("site", { bump: bumpOnce("gh-viewed:site") })
      .then((n) => { siteCountEl.textContent = formatCount(n); })
      .catch(() => { siteCountEl.textContent = "–"; });

    // Article toolbar: reads + listen only on articles.
    if (!isArticle) {
      toolbar.remove();
      return;
    }

    if (labelEl) labelEl.textContent = "Article reads";

    const anchor =
      document.querySelector("header#title-block-header") ||
      document.querySelector(".quarto-title-meta") ||
      document.querySelector("main#quarto-document-content");
    if (anchor && anchor.parentNode) {
      anchor.insertAdjacentElement("afterend", toolbar);
    }
    toolbar.hidden = false;

    readCounter(pageKey, { bump: bumpOnce(`gh-viewed:${pageKey}`) })
      .then((n) => { countEl.textContent = formatCount(n); })
      .catch(() => { countEl.textContent = "–"; });

    if (!listenRoot || !listenToggle || !listenStop || !listenStatus || !listenAudio) return;

    const slugMatch = path.match(/\/articles\/(20\d{2}-[^/]+)/);
    const audioUrl = slugMatch
      ? new URL(`../../gh-audio/${slugMatch[1]}/narration.mp3`, window.location.href).href
      : "";
    if (!audioUrl) return;

    const setIdle = () => {
      listenToggle.textContent = "Listen to this article";
      listenToggle.setAttribute("aria-pressed", "false");
      listenStop.hidden = true;
      listenStatus.textContent = "";
    };

    const setPlaying = () => {
      listenToggle.textContent = "Pause";
      listenToggle.setAttribute("aria-pressed", "true");
      listenStop.hidden = false;
      listenStatus.textContent = "Playing";
    };

    const setPaused = () => {
      listenToggle.textContent = "Resume";
      listenToggle.setAttribute("aria-pressed", "true");
      listenStop.hidden = false;
      listenStatus.textContent = "Paused";
    };

    const stop = () => {
      listenAudio.pause();
      listenAudio.currentTime = 0;
      setIdle();
    };

    fetch(audioUrl, { method: "HEAD", cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error("missing audio");
        listenAudio.src = audioUrl;
        listenRoot.hidden = false;
        setIdle();
      })
      .catch(() => {
        listenRoot.hidden = true;
      });

    listenAudio.addEventListener("play", setPlaying);
    listenAudio.addEventListener("playing", setPlaying);
    listenAudio.addEventListener("pause", () => {
      if (!listenAudio.ended && listenAudio.currentTime > 0) setPaused();
    });
    listenAudio.addEventListener("ended", setIdle);
    listenAudio.addEventListener("error", () => {
      listenStatus.textContent = "Audio could not be loaded.";
      setIdle();
    });

    listenToggle.addEventListener("click", async () => {
      if (listenAudio.paused) {
        try {
          await listenAudio.play();
        } catch (_) {
          listenStatus.textContent = "Playback was blocked by the browser.";
        }
        return;
      }
      listenAudio.pause();
    });

    listenStop.addEventListener("click", stop);
    window.addEventListener("beforeunload", stop);
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//(?:andreslanzos\.quarto\.pub|alanzos\.github\.io)(?:/|$)");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="dark">
<input type="hidden" id="giscus-alt-theme" value="light">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "alanzos/portfolio";
    script.dataset.repoId = "R_kgDOI50biQ";
    script.dataset.category = "General";
    script.dataset.categoryId = "DIC_kwDOI50bic4DCqaX";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Andres Lanzos · Basel, Switzerland</p>
</div>   
    <div class="nav-footer-center">
<p><a href="mailto:andreslanzos@gmail.com">andreslanzos@gmail.com</a></p>
</div>
    <div class="nav-footer-right">
<p><a href="https://www.linkedin.com/in/andreslanzos/">LinkedIn</a> · <a href="https://github.com/alanzos">GitHub</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>